---

- hosts: all
  become: true
  tasks:

#  - name: update repository index
#    apt:
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes


#  - name: install apache2 and php package for Ubuntu
#    apt:
#      name:
#        - apache2
#        - libapache2-mod-php
#      state: latest
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"


 # - name: add php support for apache
 #   apt:
 #     name: libapache2-mod-php
 #     state: latest
 #   when: ansible_distribution == "Ubuntu"
