---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (ubuntu)
    tags: always
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php
    tags: apache, apache2, ubunut
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default html files for site
    tags: apache,apache2,httpd
    copy:
      src: default.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariabdb
    tags: db, mariadb, ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: create gmagar user
    tags: always
    user:
      name: gmagar
      group: root

  - name: add ssh key for gmagar
    tags: always
    authorized_key:
      user: gmagar
      key: "ssh-rsa <key_of_control_machine>"

  - name: add sudoers fole for gmagar
    copy:
      src: sudoer_gmagar
      dest: /etc/sudoers.d/gmagar
      owner: root
      group: root
      mode: 0440



#    apt:
#      name:
#        - apache2
#        - libapache2-mod-php
#      state: latest
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"


 # - name: add php support for apache
 #   apt:
 #     name: libapache2-mod-php
 #     state: latest


 #   when: ansible_distribution == "Ubuntu"
